### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by hongxiaojun** [xiaolai/regular-investing-in-box#119]
1.4 我们到底在用什么定投
这是不可否认的事实：绝大多数人不做投资。为什么他们不做投资呢？他们有个共同的答案：

我根本就没有多少钱可以拿去做投资啊！

这是个过份普遍的误区，因为可用来投资的除了钱之外，还有另外一个重要资源，时间。

————
过份  应该是 “过分”。

**Comment by xiaolai** [comment]
改过来了
