### ISSUE TITLE
多了个字

### ISSUE THREAD

**Issue by cinside** [xiaolai/regular-investing-in-box#120]
2.1节
事实上，新手所能选择的最简单直接粗暴有效的策略就是沃伦·巴菲特买什么，他们就跟着买什么。根本无需妄想 “超越沃伦·巴菲特”，只要花钱买他的公司股票，就相当于能够 “跟上沃伦·巴菲特”了 —— 这不已经是最好的结果了吗？跟投沃伦·巴菲特太容易了，直接买伯克希尔·哈撒韦公司的股票就就行…… 如果新手觉得伯克希尔·哈撒韦公司的股票太贵 —— 2019 年 10 月份，伯克希尔·哈撒韦公司的股票市价约为每股 31 万美元 —— 那么可以去看看沃伦·巴菲特的持仓列表，在他持有的股票列表中选择自己想要的就好了！

> 直接买伯克希尔·哈撒韦公司的股票就就行……
多了个 "就"字

**Comment by xiaolai** [comment]
改过来了。

**Comment by xiaolai** [comment]
改过来了。
