### ISSUE TITLE
坑

### ISSUE THREAD

**Issue by vioulo** [xiaolai/regular-investing-in-box#13]
400 多人 start 了，但现在只有两个 issues。
说实话，看了介绍，感觉这又是给韭菜们挖好的坑；
能在 github 看到这本书的人大多是程序员，看来除了这个群体的其他普通人确是没有理由的接受了无限大的“踏空成本”；
17 年始，陆续看了你一些书，感觉你写书让人看的挺热血的，但是现在觉得你有点伪善:dog:

**Comment by mrguangtu** [comment]
李老师的话要听~~
