### ISSUE TITLE
如何运行 visualization.py   这个文件的代码？让数据可视化呢？

### ISSUE THREAD

**Issue by yanyongqi911** [xiaolai/regular-investing-in-box#165]
如何运行 regular-investing-in-box/data/visualization.py   这个文件的代码？让数据可视化呢？

**Comment by xiaolai** [comment]
你本地安装了 jupyterlab 就可以。当然，你看不懂这个的话，就算了。因为解释起来很费劲。从头学吧。

**Comment by xiaolai** [comment]
> 如何运行 regular-investing-in-box/data/visualization.py 这个文件的代码？让数据可视化呢？

https://gist.github.com/xiaolai/697ec3ea1607994440abf574c0f017e5

**Comment by xiaolai** [comment]
https://github.com/xiaolai/regular-investing-in-box/blob/master/data/visualization.ipynb
