### ISSUE TITLE
”这就好像 80% 的 5 次方会变成 32% 不到一样“中32%更改为33%更为精准

### ISSUE THREAD

**Issue by malicklin** [xiaolai/regular-investing-in-box#177]
https://ri.firesbox.com/#/cn/?id=_12-所谓长期它究竟是多久

> 在这个问题没有准确答案之前，“长期” 这个必要的概念基本上是 “没办法使用的” —— 任何概念，都必须清晰准确，否则就无法使用。又，由于概念必须与其它概念组合使用，大量含混的概念放在一起，就会造成精度上的巨大损失，这就好像 80% 的 5 次方会变成 32% 不到一样。在以下的阅读过程中，你会遇到若干个因为必须组合使用所以必须清晰准确才足够有效的概念。

其中，"*这就好像 80% 的 5 次方会变成 32% 不到一样*"这句话，

根据计算0.8^5=0.32768 ， 按照四舍五入，这句话应改为
*这就好像 80% 的 5 次方会变成 33% 不到一样*

这样表述更为清晰、精准， 请笑来老师确认下是否需要修改，谢谢！

Mixin ： 1090194

**Comment by xiaolai** [comment]
好的，中英韩三个版本的内容都根据你说的改了。谢谢！
