### ISSUE TITLE
第 1.2 节图表标题有误

### ISSUE THREAD

**Issue by luowenpeng** [xiaolai/regular-investing-in-box#184]
笑来老师，第 1.2 节中第一、二个图表的标题（"Bitcoin Price (2007.Jul.17 - 2019.Oct.07)"）有误，Bitcoin 的创始区块产生于北京时间 2009 年 1 月 4 日，所以上述两个图表的标题中 Bitcoin Price 的起始时间应该至少在 2009.Jan.4  这个时间点之后的。
另，笑来老师可否分享下这张图中 Bitcoin 全历史价格的数据来源，感谢！

**Comment by xiaolai** [comment]
收到，已经修改了。
