### ISSUE TITLE
关于 html 版本英文版一处翻译的疑问

### ISSUE THREAD

**Issue by xu-kai-xu** [xiaolai/regular-investing-in-box#185]
您好，我是在参加践行群英文朗读打卡活动过程中发现了一个问题。在[英文翻译版本](https://ri.firesbox.com/#/en/?id=preface)前言部分，有一段内容如下：

> It’s been ten years since I published Befriending Time, and it’s still a bestseller. While I was writing the book, I tried to adhere to the following principle:
>
> >Will this book still be useful to readers in ten years?
>
>In addition to being bestsellers, my books are often perennial sellers. **Here are my secrets for writing a book that continues to sell well over time: simple, direct, brutal and effective.**

这里，加粗的这句话，如果不是之前读过中文版本，我会理解为，**写长销书的秘诀是 simple, direct, brutal and effective**。
感觉这里英文翻译得不准确，建议改为：

> The above-mentioned principle is my secret for writing many perennial sellers, which is simple, direct, brutal and effective.

**Comment by xiaolai** [comment]
建议不错，改了。
