### ISSUE TITLE
关于第1.4小节"我们到底在用什么定投"存在困惑

### ISSUE THREAD

**Issue by RuoyuLiu-ASE** [xiaolai/regular-investing-in-box#209]
https://ri.firesbox.com/#/cn/?id=_14-%e6%88%91%e4%bb%ac%e5%88%b0%e5%ba%95%e5%9c%a8%e7%94%a8%e4%bb%80%e4%b9%88%e5%ae%9a%e6%8a%95

在第三版正文中的第1.4小节有两点不大明白，特来请教。
正文中说到：
> 虽然这样的商业模式终归有个天花板存在，但，它使得我早就摆脱了日常生活成本的束缚，并且总是有金额虽然并不巨大，但成本肯定为零，又肯定没有使用期限，并且可以源源不断地产生的资金，可用来投资…… 没有这个关键，我在投资领域的一切业绩就都不可能存在。 **所以，** 我用来定投区块链数字资产的，不仅仅是钱，还有从开始之后到现在的所有有效工作时间，以及这些有效工作时间被我多次销售之后产生的可持续增长的收入。

上面这段文字中的“所以”这个因果关系我有点困惑，这段文字的因果关系是——因为您通过写作来升级了自己的商业模式，所以是用写作的收入来进行定投么？如果是这个意思的话，您想表达的意思是：“定投的除了您的金钱之外，还有您在写作这份职业上所投入的有效时间，以及写作带来的收入”吧？

在第1.4小节中，让我困惑的第二点是：
> 总之，在李笑来看来，采用定投策略，是个人商业模式的三连胜（trifecta）式的升级：**①从一份时间只能出售一次升级到一份时间能出售很多次；** ②从只会用钱消费升级到会用钱赚钱 —— 也就是开始投资；③ 从只会用钱投资升级到不仅会用钱投资还会用时间投资……

我不明白的点是第一点：“从一份时间只能出售一次升级到一份时间能出售很多次；” 为什么说定投可以是的我们的 **一份时间** 出售很多次呢？写作或者在线授课的方式可以达到一份有效工作时间被多次销售的效果，但是定投为什么也有这样的效果呢？

读完第1.4小节，我个人的总体感受是：**首先需要去升级个人的商业模式**，才能去使用定投策略。因为就像您在书中所说的：“绝大多数人最终都是被这些生活基本成本打败的。一个人所能赚到的钱，要超过这个日益增长直至平稳最终才有所下滑的成本线，剩下的钱才是能够用来践行定投策略的部分。不升级个人商业模式，很难有什么钱剩下。”

**所以第一步应该是想办法去学习类似写作这样的技能(这里只是拿写作举例)，通过写作得到了可持续增长的收入之后，拿这份被多次出售有效时间的收入去进行定投才能在定投领域一直持续的坚持下去。**

不知道我的这个感受是否是您想传递的意思，希望笑来老师能够指点一下，谢谢您的回复！

**Comment by xiaoxianaa** [comment]
我感觉应该是这个意思

**Comment by dx-berry** [comment]
比如你上班获得一份收入，本质上你是拿自己的时间销售了一次获得了应得的报酬money，然后你拿money去定投，定投的是一个有前景并且长远来说是上涨的股票（打个比方是股票）。你不能24小时赚钱，但是，你是钱可以帮你24小时赚钱，而你的钱是通过销售一份时间获得的，那现在不就是说，你已经做到一份时间销售多次了吗？

**Comment by F4rSeer** [comment]
您的来信已收到，我会尽快回复您。

**Comment by xu-kai-xu** [comment]
@RuoyuLiu-ASE 

我也是这本书的读者，关于1.4节的那个问题，

> 我不明白的点是第一点：“从一份时间只能出售一次升级到一份时间能出售很多次；” 为什么说定投可以是的我们的 一份时间 出售很多次呢？写作或者在线授课的方式可以达到一份有效工作时间被多次销售的效果，但是定投为什么也有这样的效果呢？

我的想法是，一份时间出售多次的能力是定投的一个前提，但不能必须的前提。能做到这一点当然很好，但是没做到，也不妨碍你开始定投。只是记得慢慢培养这种能力就好。
