### ISSUE TITLE
关于 3.2节 走过路过千万不要错过 中，引用的文献“Black swans, market timing and the Dow” 的问题

### ISSUE THREAD

**Issue by xu-kai-xu** [xiaolai/regular-investing-in-box#212]
李老师好，3.2节中，提到：
> 有人在 2015 年做过统计，在此之前的 2,600 天里，如果你竟然可以避开 10 个最差的日子，那么，你的收益可能增加 104%！

对应的英文版本是：
>  In his 2009 paper "Black swans, market timing and the Dow", IESE Professor Javier Estrada calculated that, if you had been able to avoid the ten worst days in the market from 1900 to 2006, your returns would have increased by 206%!

发现这里的数字没有对上。文中的图片上的数字是 104%。所以就找了论文来看，发现论文里确实是 206%。

所以想和您确认一下，是不是图片中的数据和论文的引用有误。

**Comment by xiaolai** [comment]
已更正
