### ISSUE TITLE
英语版4.1 We Are Extremely Unreliable 一处小错误

### ISSUE THREAD

**Issue by Qidragonball** [xiaolai/regular-investing-in-box#213]
4.1 We Are Extremely Unreliable 第三段中
>For instance, [a paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2631940/) by Benedetto De Martino and his >collaborators describes an experiment in which participants were told that they had received an amount of money, such as >fifty British pounds. They were told that they would not necessarily be able to keep all of the money, but would instead >have to choose between a "sure" option, in which they would keep a portion of the money, and a "gamble" option, in >which they would either keep all of the money of lose all of the money. The expected outcomes of both options were the >same, meaning that the average results of the "gamble", if repeated over time, would be the same as the "sure" option. For >each round of the experiment, subjects were split into two groups, with the only difference being that the "sure" option >was framed in different ways...
either keep all of the money **of** lose all of the money 应该是 either keep all of the money **or** lose all of the money

**Comment by F4rSeer** [comment]
您的来信已收到，我会尽快回复您。
