### ISSUE TITLE
why https://b.watch site can’t be reached?

### ISSUE THREAD

**Issue by wangxuetao** [xiaolai/regular-investing-in-box#215]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/5194319/168326541-79b94031-0436-486e-89f2-c633acd889d1.png">

**Comment by F4rSeer** [comment]
您的来信已收到，我会尽快回复您。

**Comment by luowenpeng** [comment]
u should have a VPN

**Comment by F4rSeer** [comment]
您的来信已收到，我会尽快回复您。
