### ISSUE TITLE
感谢李老师

### ISSUE THREAD

**Issue by yang-zhang-syd** [xiaolai/regular-investing-in-box#24]
两年前跟着李老师学习了《通往财富自由之路》，可以说是帮助我重塑了自己，改变了我的人生轨迹。很多道理知道了之后感觉看到的世界竟然不一样了！

感谢您能够把自己的学识分享给大家！

**Comment by ZhuoranLyu** [comment]
> 两年前跟着李老师学习了《通往财富自由之路》，可以说是帮助我重塑了自己，改变了我的人生轨迹。很多道理知道了之后感觉看到的世界竟然不一样了！
> 
> 感谢您能够把自己的学识分享给大家！

@yang-zhang-syd 嚯嚯 把爷都给逗乐辣

**Comment by yang-zhang-syd** [comment]
@ZhuoranLyu 在李老师指点下赚了几十万，难道不该感恩？看你的ID就知道你是个没有尊严的Loser，网上自称为“爷”，生活中是个彻头彻尾的孙子。
