### ISSUE TITLE
有些具体的疑问

### ISSUE THREAD

**Issue by chaoqunlu** [xiaolai/regular-investing-in-box#3]
1.>"可供你自由支配的时间只剩下了 9 年"
不对吧，工作的理想状态，就是让自己可支配。带小孩的时候，也可以干自己的事情，也是可支配的。甚至连睡觉也是，沉睡中的思考（冥想）。

2.>“钱这个东西，它是不休息的。” 
钱投出去后，不就成了公司的股份，穿透来看：公司本身，也是要工作时间之外的休息，也是有法定节假日的。

3.中烟国际，是中烟的进出口贸易公司，卖到国外去，是一个竞争市场，跟中烟是两码事。

4.>“直接选择市场上所有人都最看好的股票。”
这里的看好，是看好该公司本身的发展（营收、利润），还是公司今后股价的上升？作者的表述，没有**price in** 的概念。好公司、贵价格，也是能害死人的。比如可口可乐、GE、戴尔、yahoo，这些也都是曾经市场上所有人“看好”的股票。

5.总是用后视镜的茅台这一只股票，去跟房产比。用一个盲点值，跟另一个市场的均值比。可是，房产的中位数，比股市的中位数涨幅，似乎大多了。

6.前一秒钟谈到短期交易是随机游走的噪音（我认同），后面又以【比特币的交易量比苹果大多了】证明区块链交易市场的NB。可是，按前一秒的逻辑，得出结论应该是比特币的交易噪音更大、投机更浓。

7.>**对资产来说，流动性是决定性因素。**如果没有流动性的话，无论多有价值的资产，都和面对敌人的时候你的手枪里虽然确实有子弹但那子弹却被卡在弹夹里就是射不出来差不多……
比喻看似精彩，但却是错的。流动性和资产价格，是可以互换的（用价差，去交易）。对资产来说，未来的增值能力，才是决定性因素。流动性大小，跟资产的好赖，没啥关系的。

......

**Comment by mrguangtu** [comment]
关于**流动性**，我是支持这个观点的。
就像以前注册了钱包，充了点钱，但是**把钱包的密码忘记了**。而这里面的钱，也等于是被“平均地分配给了所有持有这种资产的**每一个**人”了。流动性彻底没有的结局就是这个。

**Comment by chaoqunlu** [comment]
> 关于**流动性**，我是支持这个观点的。
> 就像以前注册了钱包，充了点钱，但是**把钱包的密码忘记了**。而这里面的钱，也等于是被“平均地分配给了所有持有这种资产的**每一个**人”了。流动性彻底没有的结局就是这个。

**Comment by chaoqunlu** [comment]
逻辑硬伤太多，观点与事例很多是牵强的。

**Comment by xiaolai** [comment]
@chaoqunlu 我觉得你踢的问题都挺好。我需要花点时间重新说清楚。

**Comment by hongxiaojun** [comment]
个人浅见，欢迎吐槽

1.>"可供你自由支配的时间只剩下了 9 年" 不对吧，工作的理想状态，就是让自己可支配。带小孩的时候，也可以干自己的事情，也是可支配的。甚至连睡觉也是，沉睡中的思考（冥想）。
老师举这个例子，其目的是为了说明个人努力的极限很明显。不应该去纠结这9年这个数字本身，而是以量级的思维去分析，哪怕你精打细算，按照你说的带小孩也可以做事，睡觉也可以思考事情的情况，在钱的365*24小时面前，就不是层次的。
更重要的是钱其实也是你的劳动成本，你的劳动结晶，你的资源。你用你的智慧让你使用更好利用时间，怎么就不能去花精力把更划算的金钱为你劳动，为你干活呢？
 2.>“钱这个东西，它是不休息的。” 钱投出去后，不就成了公司的股份，穿透来看：公司本身，也是要工作时间之外的休息，也是有法定节假日的。 
这个呢，人是要休息，可是如果你投的是阿里或者腾旭，人家的服务都是24小时在服务机房跑的，谷歌的广告系统也是无人看守的印钞机。你的钱投给这样的公司，公司再通过机器干活产生利润。这其实已经是不休息的为你干活了。法定假日是对公司的人，不是对整个公司系统。

3.中烟国际，是中烟的进出口贸易公司，卖到国外去，是一个竞争市场，跟中烟是两码事。
这个我还没弄懂。先过。。

 4.>“直接选择市场上所有人都最看好的股票。” 这里的看好，是看好该公司本身的发展（营收、利润），还是公司今后股价的上升？作者的表述，没有price in 的概念。好公司、贵价格，也是能害死人的。比如可口可乐、GE、戴尔、yahoo，这些也都是曾经市场上所有人“看好”的股票。
这里的看好应该就是说的各项指标都被市场认可且市场已经用最聪明的钱做出了选择。
 5.总是用后视镜的茅台这一只股票，去跟房产比。用一个盲点值，跟另一个市场的均值比。可是，房产的中位数，比股市的中位数涨幅，似乎大多了。 
兄die，您忽略了一个“最”字。
6.前一秒钟谈到短期交易是随机游走的噪音（我认同），后面又以【比特币的交易量比苹果大多了】证明区块链交易市场的NB。可是，按前一秒的逻辑，得出结论应该是比特币的交易噪音更大、投机更浓。 
一个是对个人（散户）决策而言。这里的噪音是主观称呼，其实就是随机波动，涨跌概率各50%而已。但是人们并不这么认为，因为有消息面。
交易量是对标的综合评定指标。二者并没有因果或者很大相关性吧。
7.>**对资产来说，流动性是决定性因素。**如果没有流动性的话，无论多有价值的资产，都和面对敌人的时候你的手枪里虽然确实有子弹但那子弹却被卡在弹夹里就是射不出来差不多…… 比喻看似精彩，但却是错的。流动性和资产价格，是可以互换的（用价差，去交易）。对资产来说，未来的增值能力，才是决定性因素。流动性大小，跟资产的好赖，没啥关系的。 ......
流动性差就是不值得投资，否则它就不是好标的。个人投资者流动性需求其实是很高的。比如说2011年的时候，中国发生过一次信用债大熊市，当时整个债券市场一片死寂，处于一个无价无市的状态。你想想，那时候你如果持有了债券，想买房，想换车，小孩交学费，不要说你的债券打八折，估计跳楼价都卖不出去。所以债券对流动性需求比较高的个人投资者而言，不算最佳选择。
