### ISSUE TITLE
李老师，我想郑重其事的问您BOX几个问题？

### ISSUE THREAD

**Issue by cynthiacimin** [xiaolai/regular-investing-in-box#40]
李老师，我是您的忠实听众，也是财富自由之路的读者，花钱买了MIXIN收费课程。听到关于BOX顶头的消息，我也很感兴趣，想要投资BOX。我之前有过投资比特币的经验，想问您几个问题：

我们用BTC,EOS，XIN 三种有价值的代币，换取的BOX是一个没有价值的ERC20 代币，也就是说，申购的三种币的钱包实际上是保存在李老师这里了。虽然BOX自称自己100%准备金，我也相信李老师不会跑路，但是币圈没有绝对的安全，如果存在BOX里的比特币被盗了怎么办？

我也知道任何交易所都不是绝对安全的，我们存在交易所里的比特币也可能被盗，但是交易所是营利性公司，如果被盗金额不大，可以用公司收入补偿，而且公司也有资本，总能有一些补偿资金。而BOX不收取管理费，是一个公益性的东西，那么把币存在李老师这里，李老师得不到任何收益，却要承担被盗的风险？ 一旦币被盗，BOX没有资本也没有收入，拿什么补偿？ 用户的权益怎么保护呢？ 难道李老师要拿出自己的10万个比特币作为担保吗？

**Comment by xiaolai** [comment]
这些问题全都是已经解答过的。自己找答案吧。
