### ISSUE TITLE
已关闭

### ISSUE THREAD

**Issue by bmbgj** [xiaolai/regular-investing-in-box#45]
请问投资者如果真的想投资BTC EOS XIN 为啥不能保存在自己钱包里，非要保存在李老师这里？李老师还无偿的帮你保管，还定投 哈哈哈。。

李老师给你一个毫无价值的ERC-20代币，换取你真金白银的比特币，就算什么事都没出，你最后领回了你的币，也只是运气，明白不？ 

本来投资虚拟币就是赌博，风险已经很大了，过几年你知道是涨还是跌？更要命的是我投资还不放在自己钱包里，却给了李笑来，然后拿了人家给你的一个凭证，你咋不把黄金给李老师，让李老师给你打个欠条，美其名曰定投黄金？

到时候李老师跑路到美国了，币一卷而空，你拿着你的韭菜盒子哭吧。再说一遍，就算是李笑来善心大发，你毫无事情，你也得不到任何额外的好处！

何其险恶的李狗，非法集资不成，开始以定投骗取BTC了，呸！

**Comment by blockchainguard** [comment]
说的不无道理。我还是自己定投（BTC ETH EOS）放在自己的ledger 硬件钱包里吧，有想了解安全存储数字资产的可以联系我。

**Comment by xiaolai** [comment]
立此存照。
