### ISSUE TITLE
已关闭

### ISSUE THREAD

**Issue by nova2358** [xiaolai/regular-investing-in-box#50]
1.贷款买房不能算作定投房产，因为房奴每次还贷的时候是按照**最初房子售价**去购买，而定投是按照资产**当时价格**购买。

2.用茅台股票和北京房产做对比存在着极大的幸存者偏差，因为18年前你是不知道今天茅台股票的市值这么高的。如果你今天开始定投茅台，你投的是今天市值top的公司，不是20年后市值排top的公司。所以要公平比较的话，应该用18年前买入北京房产，和买入当时市值最高的公司做对比，2001年初的时候市值最高的a股是中国石化，笑来老师怎么不用它作对比呢？

3.就算要定投市值最高的公司，也应该定投在**当时**市值最高的公司，而不是在**开始定投时**市值最高的公司。这样可以避免18年一直买中国石化的风险，所以如果box的成分一成不变的话同样存在着巨大的**机会成本**。

这些简单的小道理笑来老师肯定都明白，只是为了忽悠韭菜买box，就还是装个糊涂不告诉你们。

**Comment by xiaolai** [comment]
1. 但你忘了，房奴不是投资，每次都是负债。
2. 你阅读不够仔细，我说的是“最被看好的”，注意那个“最”字。
3. 再往后，你根本就没有读……

至于你的见解，放在这里，立此存照。

**Comment by nova2358** [comment]
1. 长期和跨越国家来看，房奴肯定是不如投股票好的。虽然短期来看靠着杠杆可以在房价快速上涨的过程中获利很多，不过最近二十年中国房产的上涨只是个特例，而且正如你所说，这是不可持续的，不过房奴好不好不重要了，其实和你书的主题关系也不大。

2. 我主要反对的是，``而你的同学选择定投茅台股票 —— 因为他就是个笨蛋，所以只能免费使用市场上最聪明的人的免费建议…… `` 18年前的时候，茅台的股票可不是市场上最聪明人的免费建议啊，2001年上市的的时候市值78亿，诚心请教，按照你书里的逻辑，**在18年前的时候，如何判断出那时候的茅台是``市场上所有人都最看好的股票``**？再进一步， **2001年的时候``市场上所有人都最看好的股票``是什么** ？如果一直只定投那一个股票，到现在收益如何？

立此存照，我支持长期看好数字货币的人定投数字火币，但是我相信参照index fund的方式定投top 10或者top50的数字火币（比如说按照[bitwise10](https://www.bitwiseinvestments.com/indexes/Bitwise-10)），大概率收益会高于BOX这样只投了btc+eos+一个参杂了个人利益的XIN，而且指数风险要小很多。只有定投了指数，才能真正避免踏空下一个茅台或者btc。
