### ISSUE TITLE
来忽悠开发者当韭菜了？

### ISSUE THREAD

**Issue by F7ionsy** [xiaolai/regular-investing-in-box#64]
不仅把Github当网盘了，还来这里忽悠人？继续割韭菜？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by SunHaozhe** [comment]
Github当网盘。。现在github已经被中国人一统天下了嘛

**Comment by diwayou** [comment]
忍不住想骂，这都些啥玩意，怪不得国外开发者骂这个国人排行，现在看到中文的基本没几个好开源项目

**Comment by justindeng0405** [comment]
真是什么东西都往github上放。爆粗.jpg

**Comment by XuChaoChi** [comment]
这star是刷的吧。。。

**Comment by LiuKaiqiang94** [comment]
Trending看到的，什么乱七八糟的就往GitHub上放。

**Comment by vi000246** [comment]
現在連Star也能刷了，github要被玩爛了
