### ISSUE TITLE
定投不是重点吧？又想来割韭菜了啊

### ISSUE THREAD

**Issue by sunalbert** [xiaolai/regular-investing-in-box#78]

**Comment by hongxiaojun** [comment]
无脑黑的人其实最惨了，因为他们都没搞懂他喷的是什么，就开喷了。心疼他们0.0001″。哈哈。韭菜都是自己割自己，血淋淋地。

**Comment by Ero-Cat** [comment]
笑来老师的书我也读过，很多观点不是很认同，对事情的分析太片面化了（懒得举例）。一概而论，就是鸡汤，很容易误导年轻人的。还有人要有自己的脑子，别人说的听一听看一看，结合自身资源去做分析，别盲目信从，韭菜不割“你”割韭谁。
